dducms/cms_app/cms_app/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path

 

urlpatterns = [
    path('adminold/', admin.site.urls),
     path('',include('masters.urls')),
     path('',include('admin_apps.urls')),
    path('',include('Client_app.urls')),
    
]

dducms/cms_app/masters/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings  
from django.conf.urls.static import static  

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('EditQualification/<int:itemid>',views.editqualification,name='edit'),
    path('qualificationlist',views.qualificationlist,name='quallist'),
    
     path('qualdelete/<int:itmid>',views.qualdelete,name='qualdelet'),

    path('addqualification/',views.addqualification,name='Addqual'),
    path('designation', views.adddesignation,name='adddes'),
    path('designationlist', views.designationlist,name='deslist'),
    path('designationedit/<int:itemid>', views.designationEdit,name='designationedit'),
    path('desdelete/<int:itemid>',views.designationDel,name="deldes"),
    path('classadd', views.classadd,name='classadd'),
    path('Division', views.division,name='division'),
    path('qualificationadd',views.qualad),
    path('studentregistration',views.studentreg,name='studreg'),
    path('studentlist',views.studentList,name='studlist'),

    path('studentedit',views.studentedit,name='studedit'),
    path('registration',views.empreg,name='empreg'),
    path('registrationlist',views.emplist,name='emplist'),
     path('registrationedit/<int:empid>',views.empedit,name='empedit'),
    path('qual',views.qual,name="kk"),

    path('product',views.addproduct),
    path('productlist',views.productlist),
    path('accounts/',include("django.contrib.auth.urls"),name="login"),
    path('logout',views.amlogout,name='log'),
    path('changepwd',views.changepwd)
]
if settings.DEBUG:  
        urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)  

dducms/cms_app/masters/models.py
from datetime import datetime
from email.policy import default
from unittest.util import _MAX_LENGTH
from django.db import models

# Create your models here.
class Qualification(models.Model):
    qname=models.CharField(max_length=200)
    status=models.IntegerField(default=1)
    #class designation
class Designation(models.Model):
    designation=models.CharField(max_length=200)
    code=models.CharField(max_length=200)
    status=models.IntegerField(default=1)

#class for adding, editting and listing   class
class Addclass(models.Model):
    classs=models.CharField(max_length=200)
    status=models.IntegerField(default=1)


class Category(models.Model):
    categoryname=models.CharField(max_length=200)
class prodcuctcategory(models.Model):
    catid = models.ForeignKey('Category', on_delete=models.CASCADE)
    productname=models.CharField(max_length=200)

class Employee(models.Model):
    Ename=models.CharField(max_length=200)
    gender=models.IntegerField()
    dob=models.DateField()
    address=models.CharField(max_length=300)
    email=models.CharField(max_length=200)
    mobile=models.CharField(max_length=100)
    datejoing=models.DateField()
    Eimage=models.ImageField(upload_to='employees',null=True)
    qualid=models.ForeignKey('Qualification', on_delete=models.CASCADE)
    desid=models.ForeignKey('Designation', on_delete=models.CASCADE)
    salary=models.IntegerField()
    salaryday=models.CharField(max_length=100)
    status=models.IntegerField(default=1)
    




    

dducms/cms_app/masters/views.py
from asyncio.windows_events import NULL
import re
from tkinter import Variable
from unicodedata import category
from unittest import result
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.template import loader
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User,auth
from django.contrib.auth import logout
from django.contrib.auth import get_user_model

from masters.models import Addclass, Designation, Qualification,Category, prodcuctcategory,Employee

# Edit qualification
def editqualification(request,itemid):
    if request.POST:
        details=Qualification.objects.get(id=itemid)
        details.qname=request.POST['fname']
        details.status=int(request.POST["statuss"]) 
        
        details.save()
        return redirect("quallist")

    details=Qualification.objects.get(id=itemid)
    result={
        'details':details,
    }
    return render(request,'EditQualification.html',result)
    


#view qualification
def qualificationlist(request):
    Details=Qualification.objects.all().values()
    listdt=loader.get_template("QualificationList.html")
    result={
        'Details':Details,
        
    }
    return HttpResponse(listdt.render(result,request))

def qualdelete(request,itmid):
    
    details=Qualification.objects.get(id=itmid)
    details.delete()
    return redirect("quallist")


@csrf_exempt
@login_required
def addqualification(request):
    if request.POST:
        message=""
        icon=0
        a=request.POST['fname']
        if Qualification.objects.filter(qname=a).exists():
            icon="warning"
            message="Qualification Already Exist"
            return render(request,'Qualification.html',{'message':message,'icon':icon})
        else:

                addqual=Qualification(qname=a)
                addqual.save()
                icon="success"
                message="Successfully added"
        
                return render(request,'Qualification.html',{'message':message,'icon':icon})
    else:
        return render(request,'Qualification.html')
    #adqual=loader.get_template("Qualification.html")
    #return HttpResponse(adqual.render())
@csrf_exempt 
def adddesignation(request):
    if request.POST:
        desig=request.POST["fname"]
        codes=request.POST["code"]
        icon=0
        if Designation.objects.filter(designation=desig).exists() and Designation.objects.filter(code=codes).exists() :
            icon="warning"
            su="Already Exist"     
            return render(request,'Designation.html',{'message':su,'icon':icon})
        else:
            adddes=Designation(designation=desig,code=codes)
            adddes.save()
            icon="success"
            su="Added Successfully"
            return render(request,'Designation.html',{'message':su, 'icon':icon})
    else:
        return render(request,'Designation.html')
    
def designationlist(request):
    details=Designation.objects.all().values()
    return render(request,'designationList.html',{'details':details})

#designation editting
def designationEdit(request,itemid):
    if request.POST:
        a=request.POST["desname"]
        b=request.POST["code"]
        c=int(request.POST["statuss"])
        details=Designation.objects.get(id=itemid)
        details.designation=a
        details.code=b
        details.status=c
        details.save()
        return redirect('deslist')

    details=Designation.objects.get(id=itemid) 
    return render(request,'DesignationEdit.html',{'details':details})


#delete designation from list
def designationDel(request,itemid):
    details=Designation.objects.get(id=itemid)
    details.delete()
    return redirect('deslist')
# add class details
@csrf_exempt
def classadd(request):
    if request.POST:
        ms=""
        icon=0
        a=request.POST['classname']
        if Addclass.objects.filter(classs=a).exists():
            icon="warning"
            return render(request,'classAdd.html',{'message':ms,'icon':icon})
        else:
            details=Addclass(classs=a)
            details.save()
            ms="success"
            return render(request,'classAdd.html',{'message':ms,'icon':icon})
        
#listitem=Addclass.objects.all().values()

    return render(request,'classAdd.html')


    
def division(request):
    return render(request,'Division.html')
def qualad(request):
    fname = request.POST.get('fname')
    return render(request,'qualificationadd.html',{'name':' welcome ........'},fname)
def studentreg(request):
    return render(request,'StudentRegistration.html')

def studentList(request):
    return render(request,'studentListing.html')
def studentedit(request):
    return render(request,'studentEdit.html')

def empreg(request):
    qualList=Qualification.objects.filter(status=1)
    desList=Designation.objects.filter(status=1)
    mismatch=""
    if request.POST:
        ename=request.POST['Ename']
        gender=request.POST["radio1"]
        dob=request.POST["dob"]
        address=request.POST["add"]
        email=request.POST["Email"]
        phone=request.POST["mobile"]
        doj=request.POST["doj"]
        qualid=int(request.POST['qual'])
        desid=int(request.POST["desig"])
        salary=request.POST["sal"]
        salday=request.POST["salday"]
        password=request.POST["pwd"]
        cpwd=request.POST["cpwd"]
        image=request.FILES['fileup']
       
        if password == cpwd:
             obj=Employee(Ename=ename,gender=gender,dob=dob,address=address,email=email,mobile=phone,datejoing=doj,salary=salary,salaryday=salday,desid_id=desid,qualid_id=qualid,Eimage=image)
             obj.save()
            
        
             userobj=User.objects.create_user(username=ename,password=password,first_name=ename,email=email)
             userobj.save()
        
             return render(request,'Registration.html',{'qualist':qualList,'deslist':desList,'mismatch':mismatch})
        else:
            mismatch="Password mismatch"
            return render(request,'Registration.html',{'qualist':qualList,'deslist':desList,'mismatch':mismatch})

    return render(request,'Registration.html',{'qualist':qualList,'deslist':desList,'mismatch':mismatch})

    #return render(request,'Registration.html')
# select employee whose corresponding designation
def emplist(request):
    #emplist=Employee.objects.all()
    emplist=Employee.objects.select_related('desid').all()
    return render(request,'RegistrationList.html',{'emplist':emplist})

def empdetailedview(request,empid):
    empdetail=Employee.objects.select_related('desid','qualid').all()
    return render(request,'RegistrationList.html',{'empdetail':empdetail})


def empedit(request,empid):
    qualList=Qualification.objects.filter(status=1)
    desList=Designation.objects.filter(status=1)
    emplist=Employee.objects.get(id=empid)
    if request.POST:
       
        emplist.Ename=request.POST['Ename'] 
        emplist.gender=request.POST["radio1"]
        emplist.dob=request.POST["dob"]
        emplist.address=request.POST["add"]
        emplist.email=request.POST["Email"]
        emplist.mobile=request.POST["mobile"]
        emplist.datejoing=request.POST["doj"]
        emplist.salary=request.POST["sal"]
        emplist.salaryday=request.POST["salday"]
        emplist.desid_id=int(request.POST["desig"])
        emplist.qualid_id=int(request.POST['qual'])
        emplist.save()
        return redirect('emplist')
    return render(request,'RegistrationEdit.html',{'emplist':emplist,'qualist':qualList,'deslist':desList})

@csrf_exempt
def qual(request):
    a=request.POST['fname']
    return render(request,'qualificationadd.html',{'name':a})

@csrf_exempt
def addproduct(request):
    if request.POST:
        
        adds=Category(categoryname=request.POST['cname'])
        adds.save()
        catid=adds.id
        i=1
        for i in range(10):
            key = "p" + str(i)
        
            if key in request.POST:
                pi=request.POST[key]
                if pi != '':
                    product=prodcuctcategory(catid_id=catid,productname=pi)
                    product.save()

    return render(request,'products.html')


def productlist(request):
    categories = Category.objects.all()

    details = []
    #product_category=""
    for i in categories:
        try:
            product_category = prodcuctcategory.objects.filter(catid_id=i.id)
            details.append({'category':i.categoryname})
            for item in product_category:
                details.append({ 'product_category':item})
        except prodcuctcategory.DoesNotExist:
             details.append({'category':i.categoryname, 'product_category':None})
    return render(request, 'productarray.html', {'details': details})

#using set method in html page 

"""def productlist(request):
    categories = Category.objects.all()
    return render(request,'productlist.html',{'categories':categories})
    """
def amlogout(request):
    auth.logout(request)
    return redirect('/accounts/login/')
def changepwd(request):
    return render(request,'changepwd.html')




   
   
    

dducms/cms_app/masters/templates/Designation copy.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Designation</title>

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static  'dist/css/adminlte.min.css' %}">
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
  <link rel="stylesheet" href="{% static 'plugins/sweetalert2-theme-bootstrap-4/bootstrap-4.min.css' %}">
  <!-- Toastr -->
  <link rel="stylesheet" href="{% static 'plugins/toastr/toastr.min.css' %}">
 
</head>
<body class="hold-transition sidebar-mini">
<div class="wrapper">
  <!-- Navbar -->
  {% include 'header.html' %}
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  {% include 'sidebar.html' %}

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Designation</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Designation</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <!-- left column -->
          <div class="col-md-6">
            <!-- general form elements -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Designation</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form method="post">
                {% csrf_token %}
                <div class="card-body">
                  <div class="form-group">
                    <label for="exampleInputEmail1">Designation</label>
                    <input type="text" class="form-control" id="exampleInputEmail1"  name="fname" placeholder="Enter Designation">
                  </div>
				    <div class="form-group">
                    <label for="exampleInputEmail1">Code</label>
                    <input type="text" class="form-control" id="exampleInputEmail1"  name="code" placeholder="Enter code">
                  </div>
                 

                   
                  </div>
            
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Submit</button>
                  
                </div>
              </form>
            </div>
            <!-- /.card -->

            <!-- general form elements -->
           
             
               
              </div>
              <!-- /.card-header -->
                
                
                  
                </div>
                
                
                  
                </div>
                
                </div>
                
                 
                </div>
            
                  
                </div>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->

            <!-- Input addon -->
      
             
                
              </div>
             
            
                 
                    
                  </div>

                </div>

            

                </div>

         

         
               
                  
                </div>

       
              

               

         
         
              </div>
              <!-- /.card-body -->
            </div>
            
              
     
    
         
                      
                    </div>
                  </div>
              
                    
                  </div>
 
                  
                    
                  </div>
                </div>
                <!-- /.card-body -->
               
              </form>
            </div>
            <!-- /.card -->

          </div>
        
         
            </div>
           
     
            
            </div>
            <!-- /.card -->
          </div>
          <!--/.col (right) -->
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  {% include 'footer.html' %}
  <script src="{% static 'plugins/sweetalert2/sweetalert2.min.js' %}"></script>
<!-- Toastr -->
<script src="{% static 'plugins/toastr/toastr.min.js' %}"></script>
{% if message != '' %}
  
     <script>
      var Toast = Swal.mixin({
      toast: true,
      position: 'top-end',
      showConfirmButton: false,
      timer: 3000
      });

   
      Toast.fire({
        icon: '{{icon}}',
        title: '{{message}}'
      })
    </script>
{% endif %}

</body>
</html>

dducms/cms_app/masters/templates/Designation.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Designation</title>

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static  'dist/css/adminlte.min.css' %}">
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
  <link rel="stylesheet" href="{% static 'plugins/sweetalert2-theme-bootstrap-4/bootstrap-4.min.css' %}">
  <!-- Toastr -->
  <link rel="stylesheet" href="{% static 'plugins/toastr/toastr.min.css' %}">
 
</head>
<body class="hold-transition sidebar-mini">
<div class="wrapper">
  <!-- Navbar -->
  {% include 'header.html' %}
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  {% include 'sidebar.html' %}

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Designation</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Designation</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <!-- left column -->
          <div class="col-md-6">
            <!-- general form elements -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Designation</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
                <form method="post">
                  {% csrf_token %}
                  <div class="card-body">
                    <div class="form-group">
                      <label for="exampleInputEmail1">Designation</label>
                      <input type="text" class="form-control" id="exampleInputEmail1"  name="fname" placeholder="Enter Designation">
                    </div>
              <div class="form-group">
                      <label for="exampleInputEmail1">Code</label>
                      <input type="text" class="form-control" id="exampleInputEmail1"  name="code" placeholder="Enter code">
                    </div>
                  

                    
                    </div>
              
                  </div>
                  <!-- /.card-body -->

                  <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Submit</button>
                    
                  </div>
                </form>
            </div>
            <!-- /.card -->

            <!-- general form elements -->
           
             
               
              </div>
              <!-- /.card-header -->
                
                
                  
                </div>
                
                
                  
                </div>
                
                </div>
                
                 
                </div>
            
                  
                </div>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->

            <!-- Input addon -->
      
             
                
              </div>
             
            
                 
                    
                  </div>

                </div>

            

                </div>

         

         
               
                  
                </div>

       
              

               

         
         
              </div>
              <!-- /.card-body -->
            </div>
            
              
     
    
         
                      
                    </div>
                  </div>
              
                    
                  </div>
 
                  
                    
                  </div>
                </div>
                <!-- /.card-body -->
               
              </form>
            </div>
            <!-- /.card -->

          </div>
        
         
            </div>
           
     
            
            </div>
            <!-- /.card -->
          </div>
          <!--/.col (right) -->
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  {% include 'footer.html' %}
  <script src="{% static 'plugins/sweetalert2/sweetalert2.min.js' %}"></script>
<!-- Toastr -->
<script src="{% static 'plugins/toastr/toastr.min.js' %}"></script>
{% if message != '' %}
  
     <script>
      var Toast = Swal.mixin({
      toast: true,
      position: 'top-end',
      showConfirmButton: false,
      timer: 3000
      });

   
      Toast.fire({
        icon: '{{icon}}',
        title: '{{message}}'
      })
    </script>
{% endif %}

</body>
</html>

dducms/cms_app/masters/templates/productlist.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Product</title>

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static  'dist/css/adminlte.min.css' %}">
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
  <link rel="stylesheet" href="{% static 'plugins/sweetalert2-theme-bootstrap-4/bootstrap-4.min.css' %}">
  <!-- Toastr -->
  <link rel="stylesheet" href="{% static 'plugins/toastr/toastr.min.css' %}">
 
</head>
<body class="hold-transition sidebar-mini">
<div class="wrapper">
  <!-- Navbar -->
  {% include 'header.html' %}
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  {% include 'sidebar.html' %}

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Products</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Product</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <!-- left column -->
          <div class="col-md-6">
            <!-- general form elements -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Poduct</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form method="post">
                {% csrf_token %}
                <div class="card-body">
                  <div class="form-group">
                    {% for i in categories %}
                      <label for="exampleInputEmail1">{{ i.categoryname }}</label>
                      
                     
                      {% for product in  i.prodcuctcategory_set.all %}
           
                   <li>
                    {% if product %}
                      <ul>
                        <label for="exampleInputEmail1">{{ product.productname }}</label>
                      </ul>
                      </li>
                        {% else %}
                        <p>No product available for this category.</p>
                    {% endif %}
                  </div>
                    </div>
                   {% endfor %}
                   {% endfor %}
                  
              </form>
            </div>
            <!-- /.card -->

            <!-- general form elements -->
           
             
               
              </div>
              <!-- /.card-header -->
                
                
                  
                </div>
                
                
                  
                </div>
                
                </div>
                
                 
                </div>
            
                  
                </div>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->

            <!-- Input addon -->
      
             
                
              </div>
             
            
                 
                    
                  </div>

                </div>

            

                </div>

         

         
               
                  
                </div>

       
              

               

         
         
              </div>
              <!-- /.card-body -->
            </div>
            
              
     
    
         
                      
                    </div>
                  </div>
              
                    
                  </div>
 
                  
                    
                  </div>
                </div>
                <!-- /.card-body -->
               
              </form>
            </div>
            <!-- /.card -->

          </div>
        
         
            </div>
           
     
            
            </div>
            <!-- /.card -->
          </div>
          <!--/.col (right) -->
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  {% include 'footer.html' %}
  <script src="{% static 'plugins/sweetalert2/sweetalert2.min.js' %}"></script>
<!-- Toastr -->
<script src="{% static 'plugins/toastr/toastr.min.js' %}"></script>
{% if message != '' %}
  
     <script>
      var Toast = Swal.mixin({
      toast: true,
      position: 'top-end',
      showConfirmButton: false,
      timer: 3000
      });

   
      Toast.fire({
        icon: '{{icon}}',
        title: '{{message}}'
      })
    </script>
{% endif %}

</body>
</html>

dducms/cms_app/masters/templates/qualificationadd.html
<html>
    <head>
        <h1>{{name}}</h1>
    </head>
</html>